{
  "openapi": "3.0.1",
  "info": {
    "title": "IVR Call",
    "description": "A plugin that cals the user and starts a conversation using GPT-3.",
    "version": "v1"
  },
  "servers": [
    {
      "url": "https://em.staging.api.onereach.ai"
    }
  ],
  "paths": {
    "/http/d37fa30a-8a83-421b-a571-b3dfe8ae4c20/ivrcall": {
      "post": {
        "operationId": "startCall",
        "summary": "Calls the user",
        "requestBody": {
          "description": "Optional description in *Markdown*",
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "number": "+13038685180"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Null response"
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "type": "object",
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string"
          }
        }
      }
    }
  }
}
